appCode: mapi

# 系统的标题
pageTitle: 文档中心

# 主题
theme: antd/diy

# api前缀
# 由于是单页应用，使用 HTML5 history 模式，需要对页面请求使用 主页 渲染
apiPrefix: /api

# 基础路径
baseURI: "/mapi"

# 后端 Java 服务接口地址
backendMap:
  development: http://localhost:9005/mock/

server:
  port: 8080
  devPort : 9005
  debugPort: 7005

dbOption:
  host : 'localhost'
  port : '3306'
  user : 'root'
  password : 'Anthony1021'
  database : 'mock'
  connectionLimit: 20
